#!/bin/bash
# https://github.com/nesro/time-tracker

logfile=./time-tracker-log.txt
time_sleep=1

#-------------------------------------------------------------------------------

time_start=$(date +%s)
verbose=0

#-------------------------------------------------------------------------------

# usage: from [to]
function time_diff {
	time_a=$1
	time_b=${2:-$(date +%s)}
	sec=$(((time_b - time_a) % 60))
	min=$((((time_b - time_a) / 60 ) % 60))
	hrs=$(((time_b - time_a) / 3600))
	
	printf "%02d:%02d:%02d" $hrs $min $sec
}

# usage: action track from [to]
function log_message {

	action=$1
	track=$2
	from=$3
	to=${4:-$(date +%s)}
	
	day=$(date +"%y.%m.%d")
	
	echo $action $track $from $to $day >>$logfile
}

# usage: action [year.month.day]
function today_total {
	
	track=$1
	day=${2:-$(date +"%y.%m.%d")}
	
	today_sum=$(grep "$track" $logfile | grep "$day" | \
		awk '{ s += $4 - $3 } END { print s }')
	
	if [[ -z $today_sum ]]; then
		today_sum_string=none
		today_sum=0
	else
		today_sum_string=$(date -u -d @$today_sum +'%H:%M:%S')
	fi
}

#-------------------------------------------------------------------------------

trap trap_exit EXIT
function trap_exit {

	case $trap_action in
	track)
		log_message track $trap_track $time_start
		if [[ $verbose = 1 ]]; then
			echo -e "\nThis track has been logged!"
		fi
		;;
	*)
		echo "Bad trap_exit action: \"$trap_action\""
		exit 1
		;;
	esac
	
	exit 0
}

function spin {
	
	time_start_string=$(date -d @$time_start +"%H:%M:%S")
	if [[ $verbose = 1 ]]; then
		echo -e "action: $trap_track\ntoday: $today_sum_string\nsince: $time_start_string"
		while :; do
			echo -ne "\relapsed: $(time_diff $time_start) total: $(time_diff $(($time_start - $today_sum)))"
			sleep $time_sleep
		done
	else
		while :; do
			echo -ne "\r$(time_diff $(($time_start - $today_sum)))"
			sleep $time_sleep
		done
	fi
}

#-------------------------------------------------------------------------------

for i in "$@"; do
	case $i in
	-v) shift
		verbose=1
		;;
	-w) shift
		trap_action=track
		trap_track=$1
		today_total $trap_track
		spin
		shift
		;;
    *)
    	;;
	esac
done

